import distribution_integers_special_residue_classes_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace distribution_integers_special_residue_classes_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end distribution_integers_special_residue_classes_theorem_canonical_lane_mathlib
end HautevilleHouse
